# Generated by Django 5.0.6 on 2024-06-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Partituras',
            name='partitura',
            field=models.ImageField(default='media/mini-imagem1.png', upload_to='partituras/'),
        ),
        migrations.AlterField(
            model_name='Partituras',
            name='tempo',
            field=models.CharField(max_length=10),
        ),
    ]
