# Generated by Django 5.1 on 2024-11-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_galeria_partitura_alter_galeria_tempo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partituras',
            table='biblioteca_partituras',
        ),
    ]
