# Generated by Django 5.1 on 2024-11-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_partituras_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partituras',
            new_name='Partitura',
        ),
        migrations.AlterModelTable(
            name='partitura',
            table='biblioteca_partitura',
        ),
    ]
